services:
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache-ports.conf:/etc/apache2/ports.conf
      - ./static/:/var/www/html_static
    depends_on:
      - db
    ports:
      - 127.0.0.1:8080:8080
    
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: user	
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: unsafe
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

